name: Lint and Build
run-name: Lint and Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install modules
      run: pnpm i
    - name: Run ESLint
      run: pnpm run lint
    - name: Run TypeScript
      run: tsc
    - name: Run Unit Tests
      run: pnpm run test
